[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://sportsmanship-app-1750609620-f0d2317caca5.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200