[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://sportsmanship-app-yuri-d62c46fdde93.herokuapp.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
